version: "3.8"

networks:
  es-network:
    driver: bridge
    
volumes:
  es-data:
    driver: local

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch-node-01
      - cluster.name=elasticsearch-cluster-01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=Password&1234
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-network
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-network